const createUsersTable = `
CREATE TABLE IF NOT EXISTS users (
    id bigint UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    email varchar(255),
    mobile_number varchar(255),
    personal_id varchar(45),
    address varchar(255),
    wallet_amount double(15,4),
    lat varchar(255),
    longitude varchar(255),
    street_number varchar(255),
    address1 varchar(255),
    address2 varchar(255),
    postcode varchar(255),
    city varchar(255),
    state varchar(255),
    country varchar(255),
    user_type int,
    handle varchar(255),
    business_type int,
    business_type_note text,
    birthdate date,
    sex int,
    profession varchar(255),
    password varchar(255),
    facebook_id varchar(255),
    twitter_id varchar(255),
    bio text,
    status bigint,
    profile_status int,
    show_email int,
    authenticator int,
    smsrecovery int,
    reminders_notification int,
    advertisement_updates_notification int,
    repost_notification int,
    sales_promotions_notification int,
    product_updates_notification int,
    newsletter_notification int,
    email_verified_at timestamp,
    remember_token varchar(100),
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at timestamp,
    profile_image varchar(255),
    image_gallery longtext,
    handle_is_public varchar(1),
    profession_is_public varchar(1),
    sex_is_public varchar(1),
    bio_is_public varchar(1),
    city_is_public varchar(1),
    rating float(10,2)
  );
`;

export default createUsersTable;